# Generated by Django 2.2.6 on 2019-10-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=200)),
            ],
        ),
    ]
